[package]
name = "aos-bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
aos-uefi-wrappers = {git = "https://github.com/simondevlp/aos-uefi-wrappers.git", branch = "master"}

[[bin]]
name = "aos-bootloader"
test = false
bench = false
